/**
 * Built-in starter packs admins can install with one click.
 * Each adds a row to industry_verticals and (optionally) some vertical_entities.
 */
export interface SeedPack {
  id: string;
  name: string;
  description: string;
  icon: string;
  enabled_modules: string[];
  terminology_overrides: Record<string, string>;
  default_dashboards: string[];
  ai_context_prompt: string;
  entities?: {
    slug: string;
    name: string;
    name_plural: string;
    description: string;
    icon: string;
    fields: Array<{ key: string; label: string; type: "text" | "textarea" | "number" | "date" | "select"; options?: string[]; required?: boolean }>;
    default_status_options: string[];
  }[];
}

export const SEED_PACKS: SeedPack[] = [
  {
    id: "construction",
    name: "Construction & Engineering",
    description: "End-to-end construction & engineering: preconstruction, site ops, QHSE, commercial, handover",
    icon: "HardHat",
    enabled_modules: [
      "programmes", "projects", "tasks", "work_packages", "milestones", "stage_gates",
      "rfis", "submittals", "drawings", "specifications", "transmittals",
      "daily_logs", "punch_list", "inspections", "snagging",
      "change_orders", "variations", "potential_change_items", "claims",
      "purchase_orders", "subcontracts", "procurement", "deliveries", "materials",
      "boq", "cost_codes", "valuations", "payment_applications", "retentions",
      "estimates", "tenders", "bids",
      "method_statements", "ra_ms", "permits_to_work", "toolbox_talks",
      "incidents_hse", "near_misses", "safety_observations", "audits",
      "quality_ncrs", "itp", "test_packs", "punch_walkdowns",
      "plant_equipment", "fleet", "site_diary", "manpower_log",
      "commissioning", "handover", "as_built", "warranty_defects", "om_manuals",
      "stakeholders", "subcontractors", "consultants",
      "risks", "issues", "lessons_learned", "reports", "team", "knowledgebase", "automations", "documents"
    ],
    terminology_overrides: {
      project: "Site Project",
      programme: "Capital Programme",
      work_package: "Work Package",
      stakeholder: "Subcontractor",
      task: "Activity",
      milestone: "Milestone",
      product: "Asset",
      sprint: "Look-Ahead",
    },
    default_dashboards: [
      "site_progress", "open_rfis", "submittal_log", "hse_dashboard",
      "cost_vs_budget", "schedule_health", "procurement_status", "punch_list_status"
    ],
    ai_context_prompt:
      "You are assisting a Construction & Engineering team operating to industry standards (NEC4/JCT/FIDIC, AIA G-series, CDM 2015, ISO 19650, ISO 45001, ISO 9001). Use construction terminology: RFIs, submittals, transmittals, drawings, specifications, BIM (LOD/LOIN), CDE, BoQ, EVM, change orders/variations, payment applications, retention, snagging/punch lists, ITP, NCRs, method statements, RAMS, permits to work, toolbox talks, near-miss reporting, commissioning, handover, O&M manuals, as-built drawings, warranty/DLP. Consider H&S, environmental, programme float, critical path, look-ahead schedules and subcontractor coordination.",
    entities: [
      // ---------- DESIGN & DOCUMENT CONTROL ----------
      {
        slug: "rfis",
        name: "RFI",
        name_plural: "RFIs",
        description: "Requests for Information raised to the design team or client",
        icon: "MessageSquare",
        fields: [
          { key: "subject", label: "Subject", type: "text", required: true },
          { key: "discipline", label: "Discipline", type: "select", options: ["architectural", "structural", "mechanical", "electrical", "plumbing", "civil", "fire", "facade", "landscape", "other"] },
          { key: "spec_section", label: "Spec Section", type: "text" },
          { key: "drawing_ref", label: "Drawing Reference", type: "text" },
          { key: "raised_by", label: "Raised By", type: "text" },
          { key: "assigned_to", label: "Assigned To", type: "text" },
          { key: "date_raised", label: "Date Raised", type: "date" },
          { key: "due_date", label: "Response Due", type: "date" },
          { key: "cost_impact", label: "Cost Impact", type: "select", options: ["none", "tbc", "minor", "major"] },
          { key: "schedule_impact", label: "Schedule Impact", type: "select", options: ["none", "tbc", "minor", "major"] },
          { key: "question", label: "Question", type: "textarea", required: true },
          { key: "response", label: "Response", type: "textarea" },
        ],
        default_status_options: ["draft", "open", "in_review", "answered", "closed", "void"],
      },
      {
        slug: "submittals",
        name: "Submittal",
        name_plural: "Submittals",
        description: "Material, shop-drawing, product and sample submittals for approval",
        icon: "FileCheck",
        fields: [
          { key: "spec_section", label: "Spec Section", type: "text", required: true },
          { key: "submittal_type", label: "Type", type: "select", options: ["product_data", "shop_drawing", "sample", "mock_up", "calculation", "method_statement", "manufacturer_cert"] },
          { key: "revision", label: "Revision", type: "text" },
          { key: "submitted_by", label: "Submitted By", type: "text" },
          { key: "reviewer", label: "Reviewer", type: "text" },
          { key: "ball_in_court", label: "Ball In Court", type: "text" },
          { key: "required_on_site", label: "Required On Site", type: "date" },
          { key: "lead_time_days", label: "Lead Time (days)", type: "number" },
        ],
        default_status_options: ["draft", "pending", "in_review", "approved", "approved_as_noted", "revise_resubmit", "rejected"],
      },
      {
        slug: "drawings",
        name: "Drawing",
        name_plural: "Drawings",
        description: "Drawing register with revisions, status and discipline tracking",
        icon: "PenTool",
        fields: [
          { key: "drawing_no", label: "Drawing Number", type: "text", required: true },
          { key: "title", label: "Title", type: "text", required: true },
          { key: "discipline", label: "Discipline", type: "select", options: ["architectural", "structural", "mechanical", "electrical", "plumbing", "civil", "fire", "facade"] },
          { key: "revision", label: "Revision", type: "text" },
          { key: "scale", label: "Scale", type: "text" },
          { key: "issued_for", label: "Issued For", type: "select", options: ["information", "review", "approval", "construction", "tender", "as_built"] },
          { key: "issue_date", label: "Issue Date", type: "date" },
        ],
        default_status_options: ["wip", "issued_for_review", "approved", "for_construction", "superseded", "as_built"],
      },
      {
        slug: "transmittals",
        name: "Transmittal",
        name_plural: "Transmittals",
        description: "Formal document/drawing transmittals between parties",
        icon: "Send",
        fields: [
          { key: "transmittal_no", label: "Transmittal No.", type: "text", required: true },
          { key: "to_party", label: "To", type: "text", required: true },
          { key: "from_party", label: "From", type: "text" },
          { key: "purpose", label: "Purpose", type: "select", options: ["for_information", "for_review", "for_approval", "for_construction", "for_record"] },
          { key: "sent_date", label: "Sent Date", type: "date" },
          { key: "items", label: "Items / Attachments", type: "textarea" },
        ],
        default_status_options: ["draft", "sent", "acknowledged", "responded", "closed"],
      },

      // ---------- COMMERCIAL & COST ----------
      {
        slug: "change-orders",
        name: "Change Order",
        name_plural: "Change Orders / Variations",
        description: "Variations, change orders and contract modifications (NEC CE / JCT VO / AIA G701)",
        icon: "FileEdit",
        fields: [
          { key: "co_number", label: "CO / Variation No.", type: "text", required: true },
          { key: "contract_ref", label: "Contract Ref", type: "text" },
          { key: "originator", label: "Originator", type: "select", options: ["client", "designer", "contractor", "subcontractor", "site_condition"] },
          { key: "reason", label: "Reason", type: "select", options: ["scope_change", "design_change", "site_condition", "regulatory", "client_request", "error_omission"] },
          { key: "cost_impact", label: "Cost Impact", type: "number" },
          { key: "time_impact_days", label: "Time Impact (days)", type: "number" },
          { key: "description", label: "Description", type: "textarea", required: true },
          { key: "justification", label: "Justification", type: "textarea" },
        ],
        default_status_options: ["draft", "pending_pricing", "submitted", "client_review", "approved", "rejected", "executed"],
      },
      {
        slug: "purchase-orders",
        name: "Purchase Order",
        name_plural: "Purchase Orders",
        description: "Material and service purchase orders with delivery tracking",
        icon: "ShoppingCart",
        fields: [
          { key: "po_number", label: "PO Number", type: "text", required: true },
          { key: "supplier", label: "Supplier", type: "text", required: true },
          { key: "cost_code", label: "Cost Code", type: "text" },
          { key: "value", label: "Value", type: "number" },
          { key: "currency", label: "Currency", type: "text" },
          { key: "required_date", label: "Required On Site", type: "date" },
          { key: "buyer", label: "Buyer", type: "text" },
        ],
        default_status_options: ["draft", "approved", "issued", "partially_received", "received", "invoiced", "closed", "cancelled"],
      },
      {
        slug: "subcontracts",
        name: "Subcontract",
        name_plural: "Subcontracts",
        description: "Subcontract packages, scope, value and key dates",
        icon: "FileSignature",
        fields: [
          { key: "package_ref", label: "Package Ref", type: "text", required: true },
          { key: "subcontractor", label: "Subcontractor", type: "text", required: true },
          { key: "trade", label: "Trade", type: "text" },
          { key: "contract_value", label: "Contract Value", type: "number" },
          { key: "form_of_contract", label: "Form of Contract", type: "select", options: ["nec4_subcontract", "jct_sub", "fidic", "bespoke", "other"] },
          { key: "start_date", label: "Start On Site", type: "date" },
          { key: "completion_date", label: "Completion", type: "date" },
          { key: "retention_pct", label: "Retention %", type: "number" },
        ],
        default_status_options: ["tender", "negotiation", "awarded", "live", "practical_completion", "final_account", "closed"],
      },
      {
        slug: "valuations",
        name: "Valuation",
        name_plural: "Valuations / Payment Apps",
        description: "Interim valuations and payment applications (AIA G702/703 / NEC PMC)",
        icon: "Receipt",
        fields: [
          { key: "valuation_no", label: "Valuation No.", type: "number", required: true },
          { key: "period_end", label: "Period End", type: "date", required: true },
          { key: "gross_value", label: "Gross Value", type: "number" },
          { key: "less_retention", label: "Less Retention", type: "number" },
          { key: "less_previous", label: "Less Previously Certified", type: "number" },
          { key: "amount_due", label: "Amount Due", type: "number" },
          { key: "submitted_by", label: "Submitted By", type: "text" },
        ],
        default_status_options: ["draft", "submitted", "under_assessment", "certified", "paid", "disputed"],
      },

      // ---------- SITE OPERATIONS ----------
      {
        slug: "daily-logs",
        name: "Daily Log",
        name_plural: "Daily Logs",
        description: "Site superintendent daily report: weather, manpower, deliveries, events",
        icon: "ClipboardList",
        fields: [
          { key: "log_date", label: "Date", type: "date", required: true },
          { key: "weather_am", label: "Weather AM", type: "text" },
          { key: "weather_pm", label: "Weather PM", type: "text" },
          { key: "temperature", label: "Temperature (°C)", type: "number" },
          { key: "manpower", label: "Total Manpower", type: "number" },
          { key: "subcontractors_on_site", label: "Subcontractors On Site", type: "textarea" },
          { key: "plant_on_site", label: "Plant / Equipment", type: "textarea" },
          { key: "deliveries", label: "Deliveries", type: "textarea" },
          { key: "visitors", label: "Visitors", type: "textarea" },
          { key: "delays", label: "Delays / Disruptions", type: "textarea" },
          { key: "notes", label: "Site Notes", type: "textarea" },
        ],
        default_status_options: ["draft", "submitted", "reviewed", "signed_off"],
      },
      {
        slug: "inspections",
        name: "Inspection",
        name_plural: "Inspections",
        description: "Pre-pour, MEP rough-in, structural, fire, building control inspections",
        icon: "SearchCheck",
        fields: [
          { key: "inspection_type", label: "Type", type: "select", options: ["pre_pour", "rebar", "mep_rough_in", "fire_stopping", "building_control", "client_witness", "third_party"] },
          { key: "location", label: "Location / Grid", type: "text", required: true },
          { key: "inspector", label: "Inspector", type: "text" },
          { key: "scheduled_date", label: "Scheduled", type: "date" },
          { key: "result", label: "Result", type: "select", options: ["pass", "pass_with_comments", "fail"] },
          { key: "notes", label: "Notes", type: "textarea" },
        ],
        default_status_options: ["scheduled", "in_progress", "passed", "failed", "rework_required", "closed"],
      },
      {
        slug: "punch-list",
        name: "Punch List Item",
        name_plural: "Punch List / Snag List",
        description: "Snagging and punch items captured during inspections and handover",
        icon: "ListChecks",
        fields: [
          { key: "location", label: "Location / Room", type: "text", required: true },
          { key: "trade", label: "Trade", type: "text" },
          { key: "priority", label: "Priority", type: "select", options: ["low", "medium", "high", "blocker_for_handover"] },
          { key: "description", label: "Description", type: "textarea", required: true },
          { key: "raised_by", label: "Raised By", type: "text" },
          { key: "assigned_to", label: "Assigned To", type: "text" },
          { key: "due_date", label: "Due Date", type: "date" },
        ],
        default_status_options: ["open", "in_progress", "ready_for_review", "verified", "closed", "rejected"],
      },

      // ---------- HEALTH, SAFETY, ENVIRONMENT (HSE / QHSE) ----------
      {
        slug: "hse-incidents",
        name: "HSE Incident",
        name_plural: "HSE Incidents",
        description: "Accidents, injuries, environmental incidents and dangerous occurrences (RIDDOR / OSHA)",
        icon: "AlertTriangle",
        fields: [
          { key: "incident_date", label: "Date", type: "date", required: true },
          { key: "incident_time", label: "Time", type: "text" },
          { key: "incident_type", label: "Type", type: "select", options: ["ltifr", "first_aid", "medical_treatment", "near_miss", "property_damage", "environmental", "dangerous_occurrence", "fatality"] },
          { key: "severity", label: "Severity", type: "select", options: ["minor", "moderate", "serious", "major", "catastrophic"], required: true },
          { key: "location", label: "Location", type: "text" },
          { key: "person_involved", label: "Person(s) Involved", type: "text" },
          { key: "body_part", label: "Body Part Affected", type: "text" },
          { key: "reportable", label: "Externally Reportable", type: "select", options: ["no", "yes_riddor", "yes_osha", "yes_environmental"] },
          { key: "narrative", label: "Narrative", type: "textarea", required: true },
          { key: "immediate_action", label: "Immediate Action Taken", type: "textarea" },
          { key: "root_cause", label: "Root Cause", type: "textarea" },
          { key: "corrective_action", label: "Corrective Action", type: "textarea" },
        ],
        default_status_options: ["reported", "under_investigation", "corrective_action", "closed", "escalated"],
      },
      {
        slug: "permits-to-work",
        name: "Permit to Work",
        name_plural: "Permits to Work",
        description: "Hot work, confined space, working at height, excavation, electrical permits",
        icon: "ShieldCheck",
        fields: [
          { key: "permit_type", label: "Permit Type", type: "select", options: ["hot_work", "confined_space", "working_at_height", "excavation", "electrical_isolation", "lifting_operation", "live_traffic"], required: true },
          { key: "location", label: "Location", type: "text", required: true },
          { key: "valid_from", label: "Valid From", type: "date" },
          { key: "valid_to", label: "Valid To", type: "date" },
          { key: "issued_to", label: "Issued To", type: "text" },
          { key: "issued_by", label: "Issued By", type: "text" },
          { key: "controls", label: "Controls / Precautions", type: "textarea" },
        ],
        default_status_options: ["requested", "issued", "active", "suspended", "closed", "expired"],
      },
      {
        slug: "ramss",
        name: "RAMS",
        name_plural: "Risk Assessments & Method Statements",
        description: "Task-specific Risk Assessments and Method Statements",
        icon: "ScrollText",
        fields: [
          { key: "activity", label: "Activity", type: "text", required: true },
          { key: "prepared_by", label: "Prepared By", type: "text" },
          { key: "reviewed_by", label: "Reviewed By", type: "text" },
          { key: "valid_until", label: "Valid Until", type: "date" },
          { key: "high_risk", label: "High-Risk Activity", type: "select", options: ["yes", "no"] },
          { key: "summary", label: "Summary of Method", type: "textarea" },
        ],
        default_status_options: ["draft", "submitted", "approved", "live", "expired", "superseded"],
      },
      {
        slug: "toolbox-talks",
        name: "Toolbox Talk",
        name_plural: "Toolbox Talks",
        description: "Site safety briefings and tool box talks attendance",
        icon: "Megaphone",
        fields: [
          { key: "topic", label: "Topic", type: "text", required: true },
          { key: "talk_date", label: "Date", type: "date", required: true },
          { key: "presenter", label: "Presenter", type: "text" },
          { key: "attendees_count", label: "Attendees", type: "number" },
          { key: "key_messages", label: "Key Messages", type: "textarea" },
        ],
        default_status_options: ["scheduled", "delivered", "cancelled"],
      },

      // ---------- QUALITY ----------
      {
        slug: "ncrs",
        name: "Non-Conformance",
        name_plural: "Non-Conformance Reports (NCRs)",
        description: "Quality non-conformance reports against specification or standards",
        icon: "BadgeAlert",
        fields: [
          { key: "ncr_no", label: "NCR No.", type: "text", required: true },
          { key: "raised_by", label: "Raised By", type: "text" },
          { key: "trade_party", label: "Trade / Party Responsible", type: "text" },
          { key: "specification_ref", label: "Specification Ref", type: "text" },
          { key: "location", label: "Location", type: "text" },
          { key: "severity", label: "Severity", type: "select", options: ["minor", "major", "critical"] },
          { key: "description", label: "Description", type: "textarea", required: true },
          { key: "proposed_disposition", label: "Proposed Disposition", type: "select", options: ["rework", "repair", "use_as_is", "reject_replace", "concession"] },
          { key: "root_cause", label: "Root Cause", type: "textarea" },
        ],
        default_status_options: ["open", "investigation", "disposition_proposed", "approved", "closed", "rejected"],
      },
      {
        slug: "itp",
        name: "ITP",
        name_plural: "Inspection & Test Plans",
        description: "Inspection and Test Plans with hold/witness/review points",
        icon: "ClipboardCheck",
        fields: [
          { key: "itp_ref", label: "ITP Reference", type: "text", required: true },
          { key: "discipline", label: "Discipline", type: "text" },
          { key: "activity", label: "Activity", type: "text" },
          { key: "hold_points", label: "Hold Points", type: "textarea" },
          { key: "witness_points", label: "Witness Points", type: "textarea" },
          { key: "acceptance_criteria", label: "Acceptance Criteria", type: "textarea" },
        ],
        default_status_options: ["draft", "approved", "in_use", "superseded"],
      },

      // ---------- PLANT & MATERIALS ----------
      {
        slug: "plant-equipment",
        name: "Plant / Equipment",
        name_plural: "Plant & Equipment",
        description: "Plant, machinery and equipment register with LOLER/PUWER inspections",
        icon: "Truck",
        fields: [
          { key: "asset_no", label: "Asset / Serial No.", type: "text", required: true },
          { key: "type", label: "Type", type: "select", options: ["crane", "mewp", "excavator", "telehandler", "generator", "compressor", "scaffold", "small_tool", "other"] },
          { key: "owner", label: "Owner / Hire Co.", type: "text" },
          { key: "on_hire_date", label: "On Hire", type: "date" },
          { key: "off_hire_date", label: "Off Hire", type: "date" },
          { key: "next_inspection", label: "Next Statutory Inspection", type: "date" },
          { key: "operator_cert", label: "Operator Certification", type: "text" },
        ],
        default_status_options: ["on_hire", "in_use", "idle", "defective", "off_hired", "quarantined"],
      },
      {
        slug: "deliveries",
        name: "Delivery",
        name_plural: "Deliveries",
        description: "Materials delivery scheduling and goods received tracking",
        icon: "PackageCheck",
        fields: [
          { key: "supplier", label: "Supplier", type: "text", required: true },
          { key: "po_ref", label: "PO Reference", type: "text" },
          { key: "scheduled_date", label: "Scheduled Date", type: "date" },
          { key: "scheduled_time", label: "Scheduled Time", type: "text" },
          { key: "vehicle_type", label: "Vehicle / Trailer", type: "text" },
          { key: "offloading_method", label: "Offloading", type: "select", options: ["forklift", "crane", "manual", "telehandler", "self_offload"] },
          { key: "quantity_received", label: "Quantity Received", type: "text" },
        ],
        default_status_options: ["scheduled", "in_transit", "arrived", "received_complete", "received_partial", "rejected", "rescheduled"],
      },

      // ---------- COMMISSIONING & HANDOVER ----------
      {
        slug: "commissioning",
        name: "Commissioning Activity",
        name_plural: "Commissioning",
        description: "Cx test packs, energisation, witnessing and acceptance",
        icon: "Power",
        fields: [
          { key: "system", label: "System", type: "text", required: true },
          { key: "test_pack_ref", label: "Test Pack Ref", type: "text" },
          { key: "stage", label: "Stage", type: "select", options: ["pre_commissioning", "commissioning", "performance_test", "integrated_systems_test", "client_witness"] },
          { key: "scheduled_date", label: "Scheduled", type: "date" },
          { key: "witnessed_by", label: "Witnessed By", type: "text" },
          { key: "result", label: "Result", type: "select", options: ["pass", "fail", "partial"] },
        ],
        default_status_options: ["planned", "in_progress", "complete", "failed", "accepted"],
      },
      {
        slug: "handover",
        name: "Handover Item",
        name_plural: "Handover / O&M",
        description: "Handover deliverables: O&M manuals, as-builts, warranties, training, asset data",
        icon: "KeyRound",
        fields: [
          { key: "deliverable", label: "Deliverable", type: "text", required: true },
          { key: "category", label: "Category", type: "select", options: ["om_manual", "as_built_drawing", "warranty", "test_certificate", "training_record", "asset_data", "spare_part", "key_register", "h_and_s_file"] },
          { key: "responsible_party", label: "Responsible Party", type: "text" },
          { key: "due_date", label: "Due Date", type: "date" },
          { key: "received_date", label: "Received Date", type: "date" },
        ],
        default_status_options: ["outstanding", "in_progress", "submitted", "accepted", "rejected"],
      },
      {
        slug: "warranty-defects",
        name: "Warranty Defect",
        name_plural: "Warranty / DLP Defects",
        description: "Defects raised during the Defects Liability Period (DLP) post-handover",
        icon: "Wrench",
        fields: [
          { key: "raised_date", label: "Date Raised", type: "date", required: true },
          { key: "location", label: "Location", type: "text" },
          { key: "responsible_party", label: "Responsible Party", type: "text" },
          { key: "trade", label: "Trade", type: "text" },
          { key: "description", label: "Description", type: "textarea", required: true },
          { key: "target_rectification", label: "Target Rectification", type: "date" },
        ],
        default_status_options: ["reported", "acknowledged", "in_progress", "rectified", "verified_closed", "disputed"],
      },
    ],
  },
  {
    id: "healthcare",
    name: "Healthcare",
    description: "Clinical projects, compliance and patient initiatives",
    icon: "Stethoscope",
    enabled_modules: ["programmes", "projects", "tasks", "risks", "issues", "reports", "knowledgebase", "incidents", "patient_cohorts"],
    terminology_overrides: { project: "Care Programme", stakeholder: "Patient Group" },
    default_dashboards: ["clinical_overview"],
    ai_context_prompt: "You are assisting a Healthcare team. Use clinical terminology, HIPAA awareness, patient outcomes.",
    entities: [
      {
        slug: "incidents",
        name: "Clinical Incident",
        name_plural: "Clinical Incidents",
        description: "Adverse events, near misses and patient safety reports",
        icon: "AlertTriangle",
        fields: [
          { key: "patient_ref", label: "Patient Reference", type: "text", required: true },
          { key: "severity", label: "Severity", type: "select", options: ["low", "moderate", "severe", "catastrophic"], required: true },
          { key: "narrative", label: "Narrative", type: "textarea", required: true },
        ],
        default_status_options: ["reported", "under_review", "resolved", "escalated"],
      },
    ],
  },
  {
    id: "manufacturing",
    name: "Manufacturing",
    description: "Production lines, work orders and quality control",
    icon: "Factory",
    enabled_modules: ["programmes", "projects", "tasks", "risks", "issues", "reports", "knowledgebase", "work_orders", "quality_checks"],
    terminology_overrides: { project: "Production Run", work_package: "Batch", stakeholder: "Supplier" },
    default_dashboards: ["throughput", "oee"],
    ai_context_prompt: "You are assisting a Manufacturing team. Reference OEE, work orders, lead time, scrap rate, supplier QA.",
    entities: [
      {
        slug: "work-orders",
        name: "Work Order",
        name_plural: "Work Orders",
        description: "Production and maintenance work orders",
        icon: "Wrench",
        fields: [
          { key: "wo_type", label: "Type", type: "select", options: ["production", "maintenance", "inspection"], required: true },
          { key: "asset", label: "Asset / Line", type: "text" },
          { key: "qty", label: "Quantity", type: "number" },
        ],
        default_status_options: ["scheduled", "in_progress", "complete", "on_hold"],
      },
    ],
  },
  {
    id: "education",
    name: "Education",
    description: "Curriculum, courses, learning outcomes and student initiatives",
    icon: "GraduationCap",
    enabled_modules: ["programmes", "projects", "tasks", "risks", "reports", "knowledgebase", "courses"],
    terminology_overrides: { programme: "Curriculum", project: "Course", stakeholder: "Student Cohort" },
    default_dashboards: ["enrolment", "outcomes"],
    ai_context_prompt: "You are assisting an Education team. Reference curriculum design, learning outcomes, accreditation, student engagement.",
    entities: [
      {
        slug: "courses",
        name: "Course",
        name_plural: "Courses",
        description: "Offered courses and modules",
        icon: "BookOpen",
        fields: [
          { key: "code", label: "Code", type: "text", required: true },
          { key: "credits", label: "Credits", type: "number" },
          { key: "level", label: "Level", type: "select", options: ["foundation", "undergrad", "grad", "post-grad"] },
        ],
        default_status_options: ["draft", "approved", "running", "retired"],
      },
    ],
  },
  {
    id: "legal",
    name: "Legal & Professional",
    description: "Matter management, deadlines, document review",
    icon: "Scale",
    enabled_modules: ["programmes", "projects", "tasks", "risks", "issues", "reports", "knowledgebase", "matters"],
    terminology_overrides: { project: "Matter", programme: "Practice Area", stakeholder: "Counterparty" },
    default_dashboards: ["matter_load", "billable_hours"],
    ai_context_prompt: "You are assisting a Legal practice. Reference matters, deadlines, conflicts checks, privilege, disclosure.",
    entities: [
      {
        slug: "matters",
        name: "Matter",
        name_plural: "Matters",
        description: "Legal matters and case files",
        icon: "Gavel",
        fields: [
          { key: "matter_type", label: "Matter Type", type: "select", options: ["litigation", "transactional", "advisory", "compliance"], required: true },
          { key: "client", label: "Client", type: "text", required: true },
          { key: "opposing", label: "Opposing Party", type: "text" },
        ],
        default_status_options: ["open", "discovery", "trial", "settled", "closed"],
      },
    ],
  },
  {
    id: "retail",
    name: "Retail & E-commerce",
    description: "Store ops, merchandising, inventory and seasonal launches",
    icon: "ShoppingBag",
    enabled_modules: ["programmes", "projects", "tasks", "risks", "issues", "reports", "knowledgebase", "store_initiatives"],
    terminology_overrides: { project: "Initiative", stakeholder: "Customer Segment" },
    default_dashboards: ["sales_lift", "shrinkage"],
    ai_context_prompt: "You are assisting a Retail team. Reference store ops, merchandising, seasonal calendar, inventory turn.",
  },
  {
    id: "non_profit",
    name: "Non-profit & NGO",
    description: "Grant programmes, donor relations, impact tracking",
    icon: "HandHeart",
    enabled_modules: ["programmes", "projects", "tasks", "risks", "reports", "knowledgebase", "grants"],
    terminology_overrides: { programme: "Programme", project: "Initiative", stakeholder: "Donor" },
    default_dashboards: ["impact", "grant_pipeline"],
    ai_context_prompt: "You are assisting a Non-profit/NGO team. Reference grants, beneficiaries, theory of change, impact measurement.",
    entities: [
      {
        slug: "grants",
        name: "Grant",
        name_plural: "Grants",
        description: "Grant applications and awards",
        icon: "Award",
        fields: [
          { key: "funder", label: "Funder", type: "text", required: true },
          { key: "amount", label: "Amount", type: "number" },
          { key: "deadline", label: "Application Deadline", type: "date" },
        ],
        default_status_options: ["prospect", "submitted", "awarded", "declined", "reporting"],
      },
    ],
  },
];
