/**
 * Built-in starter packs admins can install with one click.
 * Each adds a row to industry_verticals and (optionally) some vertical_entities.
 */
export interface SeedPack {
  id: string;
  name: string;
  description: string;
  icon: string;
  enabled_modules: string[];
  terminology_overrides: Record<string, string>;
  default_dashboards: string[];
  ai_context_prompt: string;
  entities?: {
    slug: string;
    name: string;
    name_plural: string;
    description: string;
    icon: string;
    fields: Array<{ key: string; label: string; type: "text" | "textarea" | "number" | "date" | "select"; options?: string[]; required?: boolean }>;
    default_status_options: string[];
  }[];
}

export const SEED_PACKS: SeedPack[] = [
  {
    id: "construction",
    name: "Construction & Engineering",
    description: "End-to-end construction & engineering: preconstruction, site ops, QHSE, commercial, handover",
    icon: "HardHat",
    enabled_modules: [
      "programmes", "projects", "tasks", "work_packages", "milestones", "stage_gates",
      "rfis", "submittals", "drawings", "specifications", "transmittals",
      "daily_logs", "punch_list", "inspections", "snagging",
      "change_orders", "variations", "potential_change_items", "claims",
      "purchase_orders", "subcontracts", "procurement", "deliveries", "materials",
      "boq", "cost_codes", "valuations", "payment_applications", "retentions",
      "estimates", "tenders", "bids",
      "method_statements", "ra_ms", "permits_to_work", "toolbox_talks",
      "incidents_hse", "near_misses", "safety_observations", "audits",
      "quality_ncrs", "itp", "test_packs", "punch_walkdowns",
      "plant_equipment", "fleet", "site_diary", "manpower_log",
      "commissioning", "handover", "as_built", "warranty_defects", "om_manuals",
      "stakeholders", "subcontractors", "consultants",
      "risks", "issues", "lessons_learned", "reports", "team", "knowledgebase", "automations", "documents"
    ],
    terminology_overrides: {
      project: "Site Project",
      programme: "Capital Programme",
      work_package: "Work Package",
      stakeholder: "Subcontractor",
      task: "Activity",
      milestone: "Milestone",
      product: "Asset",
      sprint: "Look-Ahead",
    },
    default_dashboards: [
      "site_progress", "open_rfis", "submittal_log", "hse_dashboard",
      "cost_vs_budget", "schedule_health", "procurement_status", "punch_list_status"
    ],
    ai_context_prompt:
      "You are assisting a Construction & Engineering team operating to industry standards (NEC4/JCT/FIDIC, AIA G-series, CDM 2015, ISO 19650, ISO 45001, ISO 9001). Use construction terminology: RFIs, submittals, transmittals, drawings, specifications, BIM (LOD/LOIN), CDE, BoQ, EVM, change orders/variations, payment applications, retention, snagging/punch lists, ITP, NCRs, method statements, RAMS, permits to work, toolbox talks, near-miss reporting, commissioning, handover, O&M manuals, as-built drawings, warranty/DLP. Consider H&S, environmental, programme float, critical path, look-ahead schedules and subcontractor coordination.",
    entities: [
      // ---------- DESIGN & DOCUMENT CONTROL ----------
      {
        slug: "rfis",
        name: "RFI",
        name_plural: "RFIs",
        description: "Requests for Information raised to the design team or client",
        icon: "MessageSquare",
        fields: [
          { key: "subject", label: "Subject", type: "text", required: true },
          { key: "discipline", label: "Discipline", type: "select", options: ["architectural", "structural", "mechanical", "electrical", "plumbing", "civil", "fire", "facade", "landscape", "other"] },
          { key: "spec_section", label: "Spec Section", type: "text" },
          { key: "drawing_ref", label: "Drawing Reference", type: "text" },
          { key: "raised_by", label: "Raised By", type: "text" },
          { key: "assigned_to", label: "Assigned To", type: "text" },
          { key: "date_raised", label: "Date Raised", type: "date" },
          { key: "due_date", label: "Response Due", type: "date" },
          { key: "cost_impact", label: "Cost Impact", type: "select", options: ["none", "tbc", "minor", "major"] },
          { key: "schedule_impact", label: "Schedule Impact", type: "select", options: ["none", "tbc", "minor", "major"] },
          { key: "question", label: "Question", type: "textarea", required: true },
          { key: "response", label: "Response", type: "textarea" },
        ],
        default_status_options: ["draft", "open", "in_review", "answered", "closed", "void"],
      },
      {
        slug: "submittals",
        name: "Submittal",
        name_plural: "Submittals",
        description: "Material, shop-drawing, product and sample submittals for approval",
        icon: "FileCheck",
        fields: [
          { key: "spec_section", label: "Spec Section", type: "text", required: true },
          { key: "submittal_type", label: "Type", type: "select", options: ["product_data", "shop_drawing", "sample", "mock_up", "calculation", "method_statement", "manufacturer_cert"] },
          { key: "revision", label: "Revision", type: "text" },
          { key: "submitted_by", label: "Submitted By", type: "text" },
          { key: "reviewer", label: "Reviewer", type: "text" },
          { key: "ball_in_court", label: "Ball In Court", type: "text" },
          { key: "required_on_site", label: "Required On Site", type: "date" },
          { key: "lead_time_days", label: "Lead Time (days)", type: "number" },
        ],
        default_status_options: ["draft", "pending", "in_review", "approved", "approved_as_noted", "revise_resubmit", "rejected"],
      },
      {
        slug: "drawings",
        name: "Drawing",
        name_plural: "Drawings",
        description: "Drawing register with revisions, status and discipline tracking",
        icon: "PenTool",
        fields: [
          { key: "drawing_no", label: "Drawing Number", type: "text", required: true },
          { key: "title", label: "Title", type: "text", required: true },
          { key: "discipline", label: "Discipline", type: "select", options: ["architectural", "structural", "mechanical", "electrical", "plumbing", "civil", "fire", "facade"] },
          { key: "revision", label: "Revision", type: "text" },
          { key: "scale", label: "Scale", type: "text" },
          { key: "issued_for", label: "Issued For", type: "select", options: ["information", "review", "approval", "construction", "tender", "as_built"] },
          { key: "issue_date", label: "Issue Date", type: "date" },
        ],
        default_status_options: ["wip", "issued_for_review", "approved", "for_construction", "superseded", "as_built"],
      },
      {
        slug: "transmittals",
        name: "Transmittal",
        name_plural: "Transmittals",
        description: "Formal document/drawing transmittals between parties",
        icon: "Send",
        fields: [
          { key: "transmittal_no", label: "Transmittal No.", type: "text", required: true },
          { key: "to_party", label: "To", type: "text", required: true },
          { key: "from_party", label: "From", type: "text" },
          { key: "purpose", label: "Purpose", type: "select", options: ["for_information", "for_review", "for_approval", "for_construction", "for_record"] },
          { key: "sent_date", label: "Sent Date", type: "date" },
          { key: "items", label: "Items / Attachments", type: "textarea" },
        ],
        default_status_options: ["draft", "sent", "acknowledged", "responded", "closed"],
      },

      // ---------- COMMERCIAL & COST ----------
      {
        slug: "change-orders",
        name: "Change Order",
        name_plural: "Change Orders / Variations",
        description: "Variations, change orders and contract modifications (NEC CE / JCT VO / AIA G701)",
        icon: "FileEdit",
        fields: [
          { key: "co_number", label: "CO / Variation No.", type: "text", required: true },
          { key: "contract_ref", label: "Contract Ref", type: "text" },
          { key: "originator", label: "Originator", type: "select", options: ["client", "designer", "contractor", "subcontractor", "site_condition"] },
          { key: "reason", label: "Reason", type: "select", options: ["scope_change", "design_change", "site_condition", "regulatory", "client_request", "error_omission"] },
          { key: "cost_impact", label: "Cost Impact", type: "number" },
          { key: "time_impact_days", label: "Time Impact (days)", type: "number" },
          { key: "description", label: "Description", type: "textarea", required: true },
          { key: "justification", label: "Justification", type: "textarea" },
        ],
        default_status_options: ["draft", "pending_pricing", "submitted", "client_review", "approved", "rejected", "executed"],
      },
      {
        slug: "purchase-orders",
        name: "Purchase Order",
        name_plural: "Purchase Orders",
        description: "Material and service purchase orders with delivery tracking",
        icon: "ShoppingCart",
        fields: [
          { key: "po_number", label: "PO Number", type: "text", required: true },
          { key: "supplier", label: "Supplier", type: "text", required: true },
          { key: "cost_code", label: "Cost Code", type: "text" },
          { key: "value", label: "Value", type: "number" },
          { key: "currency", label: "Currency", type: "text" },
          { key: "required_date", label: "Required On Site", type: "date" },
          { key: "buyer", label: "Buyer", type: "text" },
        ],
        default_status_options: ["draft", "approved", "issued", "partially_received", "received", "invoiced", "closed", "cancelled"],
      },
      {
        slug: "subcontracts",
        name: "Subcontract",
        name_plural: "Subcontracts",
        description: "Subcontract packages, scope, value and key dates",
        icon: "FileSignature",
        fields: [
          { key: "package_ref", label: "Package Ref", type: "text", required: true },
          { key: "subcontractor", label: "Subcontractor", type: "text", required: true },
          { key: "trade", label: "Trade", type: "text" },
          { key: "contract_value", label: "Contract Value", type: "number" },
          { key: "form_of_contract", label: "Form of Contract", type: "select", options: ["nec4_subcontract", "jct_sub", "fidic", "bespoke", "other"] },
          { key: "start_date", label: "Start On Site", type: "date" },
          { key: "completion_date", label: "Completion", type: "date" },
          { key: "retention_pct", label: "Retention %", type: "number" },
        ],
        default_status_options: ["tender", "negotiation", "awarded", "live", "practical_completion", "final_account", "closed"],
      },
      {
        slug: "valuations",
        name: "Valuation",
        name_plural: "Valuations / Payment Apps",
        description: "Interim valuations and payment applications (AIA G702/703 / NEC PMC)",
        icon: "Receipt",
        fields: [
          { key: "valuation_no", label: "Valuation No.", type: "number", required: true },
          { key: "period_end", label: "Period End", type: "date", required: true },
          { key: "gross_value", label: "Gross Value", type: "number" },
          { key: "less_retention", label: "Less Retention", type: "number" },
          { key: "less_previous", label: "Less Previously Certified", type: "number" },
          { key: "amount_due", label: "Amount Due", type: "number" },
          { key: "submitted_by", label: "Submitted By", type: "text" },
        ],
        default_status_options: ["draft", "submitted", "under_assessment", "certified", "paid", "disputed"],
      },

      // ---------- SITE OPERATIONS ----------
      {
        slug: "daily-logs",
        name: "Daily Log",
        name_plural: "Daily Logs",
        description: "Site superintendent daily report: weather, manpower, deliveries, events",
        icon: "ClipboardList",
        fields: [
          { key: "log_date", label: "Date", type: "date", required: true },
          { key: "weather_am", label: "Weather AM", type: "text" },
          { key: "weather_pm", label: "Weather PM", type: "text" },
          { key: "temperature", label: "Temperature (°C)", type: "number" },
          { key: "manpower", label: "Total Manpower", type: "number" },
          { key: "subcontractors_on_site", label: "Subcontractors On Site", type: "textarea" },
          { key: "plant_on_site", label: "Plant / Equipment", type: "textarea" },
          { key: "deliveries", label: "Deliveries", type: "textarea" },
          { key: "visitors", label: "Visitors", type: "textarea" },
          { key: "delays", label: "Delays / Disruptions", type: "textarea" },
          { key: "notes", label: "Site Notes", type: "textarea" },
        ],
        default_status_options: ["draft", "submitted", "reviewed", "signed_off"],
      },
      {
        slug: "inspections",
        name: "Inspection",
        name_plural: "Inspections",
        description: "Pre-pour, MEP rough-in, structural, fire, building control inspections",
        icon: "SearchCheck",
        fields: [
          { key: "inspection_type", label: "Type", type: "select", options: ["pre_pour", "rebar", "mep_rough_in", "fire_stopping", "building_control", "client_witness", "third_party"] },
          { key: "location", label: "Location / Grid", type: "text", required: true },
          { key: "inspector", label: "Inspector", type: "text" },
          { key: "scheduled_date", label: "Scheduled", type: "date" },
          { key: "result", label: "Result", type: "select", options: ["pass", "pass_with_comments", "fail"] },
          { key: "notes", label: "Notes", type: "textarea" },
        ],
        default_status_options: ["scheduled", "in_progress", "passed", "failed", "rework_required", "closed"],
      },
      {
        slug: "punch-list",
        name: "Punch List Item",
        name_plural: "Punch List / Snag List",
        description: "Snagging and punch items captured during inspections and handover",
        icon: "ListChecks",
        fields: [
          { key: "location", label: "Location / Room", type: "text", required: true },
          { key: "trade", label: "Trade", type: "text" },
          { key: "priority", label: "Priority", type: "select", options: ["low", "medium", "high", "blocker_for_handover"] },
          { key: "description", label: "Description", type: "textarea", required: true },
          { key: "raised_by", label: "Raised By", type: "text" },
          { key: "assigned_to", label: "Assigned To", type: "text" },
          { key: "due_date", label: "Due Date", type: "date" },
        ],
        default_status_options: ["open", "in_progress", "ready_for_review", "verified", "closed", "rejected"],
      },

      // ---------- HEALTH, SAFETY, ENVIRONMENT (HSE / QHSE) ----------
      {
        slug: "hse-incidents",
        name: "HSE Incident",
        name_plural: "HSE Incidents",
        description: "Accidents, injuries, environmental incidents and dangerous occurrences (RIDDOR / OSHA)",
        icon: "AlertTriangle",
        fields: [
          { key: "incident_date", label: "Date", type: "date", required: true },
          { key: "incident_time", label: "Time", type: "text" },
          { key: "incident_type", label: "Type", type: "select", options: ["ltifr", "first_aid", "medical_treatment", "near_miss", "property_damage", "environmental", "dangerous_occurrence", "fatality"] },
          { key: "severity", label: "Severity", type: "select", options: ["minor", "moderate", "serious", "major", "catastrophic"], required: true },
          { key: "location", label: "Location", type: "text" },
          { key: "person_involved", label: "Person(s) Involved", type: "text" },
          { key: "body_part", label: "Body Part Affected", type: "text" },
          { key: "reportable", label: "Externally Reportable", type: "select", options: ["no", "yes_riddor", "yes_osha", "yes_environmental"] },
          { key: "narrative", label: "Narrative", type: "textarea", required: true },
          { key: "immediate_action", label: "Immediate Action Taken", type: "textarea" },
          { key: "root_cause", label: "Root Cause", type: "textarea" },
          { key: "corrective_action", label: "Corrective Action", type: "textarea" },
        ],
        default_status_options: ["reported", "under_investigation", "corrective_action", "closed", "escalated"],
      },
      {
        slug: "permits-to-work",
        name: "Permit to Work",
        name_plural: "Permits to Work",
        description: "Hot work, confined space, working at height, excavation, electrical permits",
        icon: "ShieldCheck",
        fields: [
          { key: "permit_type", label: "Permit Type", type: "select", options: ["hot_work", "confined_space", "working_at_height", "excavation", "electrical_isolation", "lifting_operation", "live_traffic"], required: true },
          { key: "location", label: "Location", type: "text", required: true },
          { key: "valid_from", label: "Valid From", type: "date" },
          { key: "valid_to", label: "Valid To", type: "date" },
          { key: "issued_to", label: "Issued To", type: "text" },
          { key: "issued_by", label: "Issued By", type: "text" },
          { key: "controls", label: "Controls / Precautions", type: "textarea" },
        ],
        default_status_options: ["requested", "issued", "active", "suspended", "closed", "expired"],
      },
      {
        slug: "ramss",
        name: "RAMS",
        name_plural: "Risk Assessments & Method Statements",
        description: "Task-specific Risk Assessments and Method Statements",
        icon: "ScrollText",
        fields: [
          { key: "activity", label: "Activity", type: "text", required: true },
          { key: "prepared_by", label: "Prepared By", type: "text" },
          { key: "reviewed_by", label: "Reviewed By", type: "text" },
          { key: "valid_until", label: "Valid Until", type: "date" },
          { key: "high_risk", label: "High-Risk Activity", type: "select", options: ["yes", "no"] },
          { key: "summary", label: "Summary of Method", type: "textarea" },
        ],
        default_status_options: ["draft", "submitted", "approved", "live", "expired", "superseded"],
      },
      {
        slug: "toolbox-talks",
        name: "Toolbox Talk",
        name_plural: "Toolbox Talks",
        description: "Site safety briefings and tool box talks attendance",
        icon: "Megaphone",
        fields: [
          { key: "topic", label: "Topic", type: "text", required: true },
          { key: "talk_date", label: "Date", type: "date", required: true },
          { key: "presenter", label: "Presenter", type: "text" },
          { key: "attendees_count", label: "Attendees", type: "number" },
          { key: "key_messages", label: "Key Messages", type: "textarea" },
        ],
        default_status_options: ["scheduled", "delivered", "cancelled"],
      },

      // ---------- QUALITY ----------
      {
        slug: "ncrs",
        name: "Non-Conformance",
        name_plural: "Non-Conformance Reports (NCRs)",
        description: "Quality non-conformance reports against specification or standards",
        icon: "BadgeAlert",
        fields: [
          { key: "ncr_no", label: "NCR No.", type: "text", required: true },
          { key: "raised_by", label: "Raised By", type: "text" },
          { key: "trade_party", label: "Trade / Party Responsible", type: "text" },
          { key: "specification_ref", label: "Specification Ref", type: "text" },
          { key: "location", label: "Location", type: "text" },
          { key: "severity", label: "Severity", type: "select", options: ["minor", "major", "critical"] },
          { key: "description", label: "Description", type: "textarea", required: true },
          { key: "proposed_disposition", label: "Proposed Disposition", type: "select", options: ["rework", "repair", "use_as_is", "reject_replace", "concession"] },
          { key: "root_cause", label: "Root Cause", type: "textarea" },
        ],
        default_status_options: ["open", "investigation", "disposition_proposed", "approved", "closed", "rejected"],
      },
      {
        slug: "itp",
        name: "ITP",
        name_plural: "Inspection & Test Plans",
        description: "Inspection and Test Plans with hold/witness/review points",
        icon: "ClipboardCheck",
        fields: [
          { key: "itp_ref", label: "ITP Reference", type: "text", required: true },
          { key: "discipline", label: "Discipline", type: "text" },
          { key: "activity", label: "Activity", type: "text" },
          { key: "hold_points", label: "Hold Points", type: "textarea" },
          { key: "witness_points", label: "Witness Points", type: "textarea" },
          { key: "acceptance_criteria", label: "Acceptance Criteria", type: "textarea" },
        ],
        default_status_options: ["draft", "approved", "in_use", "superseded"],
      },

      // ---------- PLANT & MATERIALS ----------
      {
        slug: "plant-equipment",
        name: "Plant / Equipment",
        name_plural: "Plant & Equipment",
        description: "Plant, machinery and equipment register with LOLER/PUWER inspections",
        icon: "Truck",
        fields: [
          { key: "asset_no", label: "Asset / Serial No.", type: "text", required: true },
          { key: "type", label: "Type", type: "select", options: ["crane", "mewp", "excavator", "telehandler", "generator", "compressor", "scaffold", "small_tool", "other"] },
          { key: "owner", label: "Owner / Hire Co.", type: "text" },
          { key: "on_hire_date", label: "On Hire", type: "date" },
          { key: "off_hire_date", label: "Off Hire", type: "date" },
          { key: "next_inspection", label: "Next Statutory Inspection", type: "date" },
          { key: "operator_cert", label: "Operator Certification", type: "text" },
        ],
        default_status_options: ["on_hire", "in_use", "idle", "defective", "off_hired", "quarantined"],
      },
      {
        slug: "deliveries",
        name: "Delivery",
        name_plural: "Deliveries",
        description: "Materials delivery scheduling and goods received tracking",
        icon: "PackageCheck",
        fields: [
          { key: "supplier", label: "Supplier", type: "text", required: true },
          { key: "po_ref", label: "PO Reference", type: "text" },
          { key: "scheduled_date", label: "Scheduled Date", type: "date" },
          { key: "scheduled_time", label: "Scheduled Time", type: "text" },
          { key: "vehicle_type", label: "Vehicle / Trailer", type: "text" },
          { key: "offloading_method", label: "Offloading", type: "select", options: ["forklift", "crane", "manual", "telehandler", "self_offload"] },
          { key: "quantity_received", label: "Quantity Received", type: "text" },
        ],
        default_status_options: ["scheduled", "in_transit", "arrived", "received_complete", "received_partial", "rejected", "rescheduled"],
      },

      // ---------- COMMISSIONING & HANDOVER ----------
      {
        slug: "commissioning",
        name: "Commissioning Activity",
        name_plural: "Commissioning",
        description: "Cx test packs, energisation, witnessing and acceptance",
        icon: "Power",
        fields: [
          { key: "system", label: "System", type: "text", required: true },
          { key: "test_pack_ref", label: "Test Pack Ref", type: "text" },
          { key: "stage", label: "Stage", type: "select", options: ["pre_commissioning", "commissioning", "performance_test", "integrated_systems_test", "client_witness"] },
          { key: "scheduled_date", label: "Scheduled", type: "date" },
          { key: "witnessed_by", label: "Witnessed By", type: "text" },
          { key: "result", label: "Result", type: "select", options: ["pass", "fail", "partial"] },
        ],
        default_status_options: ["planned", "in_progress", "complete", "failed", "accepted"],
      },
      {
        slug: "handover",
        name: "Handover Item",
        name_plural: "Handover / O&M",
        description: "Handover deliverables: O&M manuals, as-builts, warranties, training, asset data",
        icon: "KeyRound",
        fields: [
          { key: "deliverable", label: "Deliverable", type: "text", required: true },
          { key: "category", label: "Category", type: "select", options: ["om_manual", "as_built_drawing", "warranty", "test_certificate", "training_record", "asset_data", "spare_part", "key_register", "h_and_s_file"] },
          { key: "responsible_party", label: "Responsible Party", type: "text" },
          { key: "due_date", label: "Due Date", type: "date" },
          { key: "received_date", label: "Received Date", type: "date" },
        ],
        default_status_options: ["outstanding", "in_progress", "submitted", "accepted", "rejected"],
      },
      {
        slug: "warranty-defects",
        name: "Warranty Defect",
        name_plural: "Warranty / DLP Defects",
        description: "Defects raised during the Defects Liability Period (DLP) post-handover",
        icon: "Wrench",
        fields: [
          { key: "raised_date", label: "Date Raised", type: "date", required: true },
          { key: "location", label: "Location", type: "text" },
          { key: "responsible_party", label: "Responsible Party", type: "text" },
          { key: "trade", label: "Trade", type: "text" },
          { key: "description", label: "Description", type: "textarea", required: true },
          { key: "target_rectification", label: "Target Rectification", type: "date" },
        ],
        default_status_options: ["reported", "acknowledged", "in_progress", "rectified", "verified_closed", "disputed"],
      },
    ],
  },
  {
    id: "professional_services",
    name: "Professional Services & Consulting",
    description: "End-to-end PS&C: pipeline, engagements, SOWs, staffing, time, billing, deliverables, QA",
    icon: "Briefcase",
    enabled_modules: [
      "programmes", "projects", "tasks", "work_packages", "milestones", "stage_gates",
      "engagements", "retainers", "msa", "sow", "change_orders", "client_renewals",
      "opportunities", "proposals", "rfp_responses", "pricing_models", "win_loss",
      "deliverables", "acceptance", "qa_reviews", "engagement_health", "scope_change_log",
      "staffing_requests", "resource_plan", "bench", "skills_matrix", "utilisation",
      "timesheets", "expenses", "wip", "billing", "invoices", "revenue_recognition",
      "client_satisfaction", "nps", "case_studies", "references",
      "risks", "issues", "lessons_learned", "reports", "team", "knowledgebase", "automations", "documents",
    ],
    terminology_overrides: {
      project: "Engagement",
      programme: "Account",
      work_package: "Workstream",
      stakeholder: "Client Contact",
      task: "Activity",
      product: "Service Offering",
      sprint: "Sprint",
      milestone: "Milestone",
    },
    default_dashboards: [
      "engagement_portfolio", "utilisation_heatmap", "pipeline_funnel",
      "wip_aged", "billing_realisation", "csat_nps", "deliverable_health",
    ],
    ai_context_prompt:
      "You are assisting a Professional Services & Consulting firm operating to industry standards (SPI Research PS Maturity, ITIL 4 for managed services, MSF/Agile/Waterfall delivery, ISO 20700 management consultancy, AICPA/ASC 606 / IFRS 15 revenue recognition). Use PS terminology: Master Services Agreement (MSA), Statement of Work (SOW), Change Order, Engagement, Workstream, Deliverable & Acceptance, Time & Materials vs Fixed-Fee vs Capped vs Retainer, Utilisation, Realisation, Bill rate, Cost rate, Effective rate, WIP, Aged WIP, Lock-up days, Bench, Resource plan, RFP / RFI / RFQ, Bid/no-bid, Win-loss, NPS / CSAT, QA review, Engagement health (RAG), Scope creep, Margin erosion. Consider risk on fixed-fee work, conflicts of interest, professional ethics and independence, data protection in client environments.",
    entities: [
      // ---------- SALES & PIPELINE ----------
      {
        slug: "opportunities",
        name: "Opportunity",
        name_plural: "Opportunities / Pipeline",
        description: "Qualified pipeline with weighted forecast, BANT/MEDDIC qualification",
        icon: "Target",
        fields: [
          { key: "client", label: "Client / Prospect", type: "text", required: true },
          { key: "service_line", label: "Service Line", type: "select", options: ["strategy", "transformation", "technology", "data_analytics", "change_mgmt", "managed_services", "training", "advisory", "other"] },
          { key: "deal_value", label: "Deal Value", type: "number" },
          { key: "currency", label: "Currency", type: "text" },
          { key: "stage", label: "Stage", type: "select", options: ["lead", "qualified", "discovery", "proposal", "negotiation", "verbal", "closed_won", "closed_lost"] },
          { key: "probability", label: "Win Probability %", type: "number" },
          { key: "expected_close", label: "Expected Close", type: "date" },
          { key: "qualification", label: "Qualification (BANT/MEDDIC notes)", type: "textarea" },
          { key: "competitor", label: "Known Competitors", type: "text" },
          { key: "owner", label: "Sales Owner", type: "text" },
        ],
        default_status_options: ["open", "won", "lost", "no_decision", "withdrawn"],
      },
      {
        slug: "proposals",
        name: "Proposal",
        name_plural: "Proposals & RFP Responses",
        description: "Proposals, RFP/RFI/RFQ responses with bid/no-bid decisions",
        icon: "FileSpreadsheet",
        fields: [
          { key: "client", label: "Client", type: "text", required: true },
          { key: "opportunity_ref", label: "Opportunity Ref", type: "text" },
          { key: "proposal_type", label: "Type", type: "select", options: ["unsolicited_proposal", "rfp_response", "rfi_response", "rfq_response", "loi", "framework_call_off"] },
          { key: "submission_due", label: "Submission Due", type: "date" },
          { key: "estimated_value", label: "Estimated Value", type: "number" },
          { key: "pricing_model", label: "Pricing Model", type: "select", options: ["time_materials", "fixed_fee", "capped_tm", "milestone", "retainer", "outcome_based", "hybrid"] },
          { key: "bid_no_bid", label: "Bid / No-Bid Decision", type: "select", options: ["pending", "bid", "no_bid"] },
          { key: "go_no_go_owner", label: "Go/No-Go Approver", type: "text" },
          { key: "win_strategy", label: "Win Strategy / Themes", type: "textarea" },
        ],
        default_status_options: ["draft", "under_review", "submitted", "shortlisted", "won", "lost", "withdrawn"],
      },

      // ---------- CONTRACTS ----------
      {
        slug: "msa",
        name: "MSA",
        name_plural: "Master Services Agreements",
        description: "Master Services Agreements — umbrella legal terms with the client",
        icon: "FileSignature",
        fields: [
          { key: "client", label: "Client", type: "text", required: true },
          { key: "msa_ref", label: "MSA Reference", type: "text" },
          { key: "effective_date", label: "Effective Date", type: "date" },
          { key: "expiry_date", label: "Expiry Date", type: "date" },
          { key: "auto_renewal", label: "Auto-Renewal", type: "select", options: ["yes", "no"] },
          { key: "governing_law", label: "Governing Law", type: "text" },
          { key: "liability_cap", label: "Liability Cap", type: "text", },
          { key: "ip_terms", label: "IP / Work-Product Terms", type: "select", options: ["client_owns", "consultant_owns", "joint", "license_back"] },
          { key: "key_terms", label: "Other Key Terms", type: "textarea", },
        ],
        default_status_options: ["draft", "in_negotiation", "executed", "active", "expired", "terminated"],
      },
      {
        slug: "sow",
        name: "SOW",
        name_plural: "Statements of Work",
        description: "Engagement-specific Statement of Work under an MSA",
        icon: "FileText",
        fields: [
          { key: "sow_ref", label: "SOW Reference", type: "text", required: true },
          { key: "client", label: "Client", type: "text", required: true },
          { key: "msa_ref", label: "Parent MSA Ref", type: "text" },
          { key: "engagement_name", label: "Engagement Name", type: "text" },
          { key: "pricing_model", label: "Pricing Model", type: "select", options: ["time_materials", "fixed_fee", "capped_tm", "milestone", "retainer", "outcome_based", "hybrid"] },
          { key: "contract_value", label: "Contract Value", type: "number" },
          { key: "currency", label: "Currency", type: "text" },
          { key: "start_date", label: "Start Date", type: "date" },
          { key: "end_date", label: "End Date", type: "date" },
          { key: "scope_summary", label: "Scope Summary", type: "textarea", required: true },
          { key: "deliverables_summary", label: "Key Deliverables", type: "textarea" },
          { key: "assumptions", label: "Assumptions & Dependencies", type: "textarea" },
          { key: "acceptance_criteria", label: "Acceptance Criteria", type: "textarea" },
        ],
        default_status_options: ["draft", "client_review", "executed", "live", "complete", "closed", "terminated"],
      },
      {
        slug: "change-orders",
        name: "Change Order",
        name_plural: "Change Orders",
        description: "Scope, fee or schedule changes to a live SOW",
        icon: "FileEdit",
        fields: [
          { key: "co_number", label: "CO No.", type: "text", required: true },
          { key: "sow_ref", label: "Parent SOW Ref", type: "text", required: true },
          { key: "reason", label: "Reason", type: "select", options: ["scope_change", "additional_request", "schedule_change", "rate_change", "rework", "client_delay"] },
          { key: "fee_impact", label: "Fee Impact", type: "number" },
          { key: "schedule_impact_days", label: "Schedule Impact (days)", type: "number" },
          { key: "description", label: "Description", type: "textarea", required: true },
          { key: "justification", label: "Justification", type: "textarea" },
        ],
        default_status_options: ["draft", "internal_approval", "submitted", "client_review", "approved", "rejected", "executed"],
      },
      {
        slug: "retainers",
        name: "Retainer",
        name_plural: "Retainers",
        description: "Recurring monthly/quarterly retainer agreements with hour banks",
        icon: "RefreshCcw",
        fields: [
          { key: "client", label: "Client", type: "text", required: true },
          { key: "retainer_type", label: "Type", type: "select", options: ["advisory", "managed_service", "support", "block_hours", "outcome_based"] },
          { key: "monthly_value", label: "Monthly Value", type: "number" },
          { key: "hours_included", label: "Hours Included / Month", type: "number" },
          { key: "rollover_policy", label: "Hour Rollover Policy", type: "select", options: ["no_rollover", "rollover_30d", "rollover_quarter", "use_or_lose"] },
          { key: "term_months", label: "Term (months)", type: "number" },
          { key: "renewal_notice_days", label: "Renewal Notice (days)", type: "number" },
        ],
        default_status_options: ["draft", "active", "paused", "renewing", "expired", "terminated"],
      },

      // ---------- ENGAGEMENT DELIVERY ----------
      {
        slug: "engagements",
        name: "Engagement",
        name_plural: "Engagements",
        description: "Active client engagements with health, margin and burn-rate tracking",
        icon: "Handshake",
        fields: [
          { key: "client", label: "Client", type: "text", required: true },
          { key: "sow_ref", label: "SOW Ref", type: "text" },
          { key: "engagement_partner", label: "Engagement Partner / Sponsor", type: "text" },
          { key: "engagement_manager", label: "Engagement Manager", type: "text" },
          { key: "delivery_method", label: "Delivery Method", type: "select", options: ["waterfall", "agile", "hybrid", "advisory", "managed_service"] },
          { key: "rag_status", label: "Health (RAG)", type: "select", options: ["green", "amber", "red"] },
          { key: "contract_value", label: "Contract Value", type: "number" },
          { key: "budget_hours", label: "Budgeted Hours", type: "number" },
          { key: "hours_to_date", label: "Hours to Date", type: "number" },
          { key: "etc_hours", label: "Estimate to Complete (hrs)", type: "number" },
          { key: "margin_target_pct", label: "Target Margin %", type: "number" },
          { key: "margin_actual_pct", label: "Actual Margin %", type: "number" },
        ],
        default_status_options: ["mobilising", "live", "at_risk", "paused", "closing", "complete", "post_engagement_review"],
      },
      {
        slug: "deliverables",
        name: "Deliverable",
        name_plural: "Deliverables",
        description: "Contractual deliverables tracked to acceptance with sign-off",
        icon: "PackageCheck",
        fields: [
          { key: "deliverable_ref", label: "Deliverable Ref", type: "text", required: true },
          { key: "title", label: "Title", type: "text", required: true },
          { key: "engagement_ref", label: "Engagement Ref", type: "text" },
          { key: "sow_clause", label: "SOW Clause / Section", type: "text" },
          { key: "owner", label: "Owner (consultant)", type: "text" },
          { key: "acceptance_criteria", label: "Acceptance Criteria", type: "textarea", required: true },
          { key: "due_date", label: "Due Date", type: "date" },
          { key: "submitted_date", label: "Submitted Date", type: "date" },
          { key: "accepted_date", label: "Accepted Date", type: "date" },
          { key: "client_signoff_by", label: "Client Sign-off By", type: "text" },
          { key: "fee_milestone", label: "Linked Fee Milestone", type: "text" },
        ],
        default_status_options: ["not_started", "in_progress", "internal_qa", "submitted", "client_review", "revisions_requested", "accepted", "rejected", "waived"],
      },
      {
        slug: "qa-reviews",
        name: "QA Review",
        name_plural: "QA Reviews",
        description: "Internal quality reviews of deliverables before client submission",
        icon: "ClipboardCheck",
        fields: [
          { key: "deliverable_ref", label: "Deliverable Ref", type: "text", required: true },
          { key: "review_type", label: "Review Type", type: "select", options: ["technical_review", "partner_review", "risk_compliance", "editorial", "independent_review"] },
          { key: "reviewer", label: "Reviewer", type: "text" },
          { key: "review_date", label: "Review Date", type: "date" },
          { key: "rating", label: "Quality Rating", type: "select", options: ["needs_rework", "minor_changes", "approved_with_comments", "approved"] },
          { key: "findings", label: "Findings", type: "textarea" },
        ],
        default_status_options: ["scheduled", "in_progress", "complete", "rework_required", "signed_off"],
      },
      {
        slug: "scope-changes",
        name: "Scope Change",
        name_plural: "Scope Change Log",
        description: "Log of scope changes — captures creep before it erodes margin",
        icon: "GitBranch",
        fields: [
          { key: "engagement_ref", label: "Engagement Ref", type: "text", required: true },
          { key: "raised_by", label: "Raised By", type: "text" },
          { key: "client_or_internal", label: "Source", type: "select", options: ["client_request", "internal_discovery", "regulatory", "design_change"] },
          { key: "estimated_effort_hours", label: "Estimated Effort (hrs)", type: "number" },
          { key: "billable", label: "Treatment", type: "select", options: ["absorbed", "change_order_required", "goodwill", "rejected"] },
          { key: "description", label: "Description", type: "textarea", required: true },
        ],
        default_status_options: ["logged", "under_assessment", "co_drafted", "co_approved", "absorbed", "rejected"],
      },

      // ---------- STAFFING & RESOURCES ----------
      {
        slug: "staffing-requests",
        name: "Staffing Request",
        name_plural: "Staffing Requests",
        description: "Demand for consultants on engagements — driven into the resource plan",
        icon: "UserPlus",
        fields: [
          { key: "engagement_ref", label: "Engagement Ref", type: "text", required: true },
          { key: "role", label: "Role", type: "text", required: true },
          { key: "level", label: "Level", type: "select", options: ["analyst", "consultant", "senior_consultant", "manager", "senior_manager", "director", "partner"] },
          { key: "skills_required", label: "Skills Required", type: "textarea" },
          { key: "start_date", label: "Start Date", type: "date" },
          { key: "end_date", label: "End Date", type: "date" },
          { key: "allocation_pct", label: "Allocation %", type: "number" },
          { key: "location", label: "Location / Onsite Required", type: "text" },
          { key: "rate_card", label: "Rate Card / Bill Rate", type: "text" },
        ],
        default_status_options: ["open", "candidates_proposed", "interviewed", "filled", "filled_external", "withdrawn"],
      },
      {
        slug: "skills-matrix",
        name: "Skill Profile",
        name_plural: "Skills Matrix",
        description: "Per-consultant skills inventory with proficiency levels",
        icon: "Layers",
        fields: [
          { key: "consultant", label: "Consultant", type: "text", required: true },
          { key: "skill", label: "Skill / Capability", type: "text", required: true },
          { key: "proficiency", label: "Proficiency", type: "select", options: ["awareness", "working", "practitioner", "expert", "thought_leader"] },
          { key: "years_experience", label: "Years Experience", type: "number" },
          { key: "certifications", label: "Relevant Certifications", type: "text" },
          { key: "last_used", label: "Last Used", type: "date" },
        ],
        default_status_options: ["self_assessed", "manager_validated", "needs_review"],
      },

      // ---------- TIME, EXPENSES & BILLING ----------
      {
        slug: "expenses",
        name: "Expense",
        name_plural: "Expense Claims",
        description: "Project & travel expenses (rebillable to client where contracted)",
        icon: "Wallet",
        fields: [
          { key: "engagement_ref", label: "Engagement Ref", type: "text" },
          { key: "consultant", label: "Consultant", type: "text", required: true },
          { key: "category", label: "Category", type: "select", options: ["travel_air", "travel_rail", "accommodation", "subsistence", "mileage", "client_entertainment", "training", "subscription", "other"] },
          { key: "amount", label: "Amount", type: "number", required: true },
          { key: "currency", label: "Currency", type: "text" },
          { key: "expense_date", label: "Expense Date", type: "date" },
          { key: "rebillable", label: "Re-billable to Client", type: "select", options: ["yes", "no", "with_markup"] },
          { key: "receipt_ref", label: "Receipt Reference", type: "text" },
        ],
        default_status_options: ["draft", "submitted", "manager_approved", "finance_approved", "rejected", "reimbursed", "billed_to_client"],
      },
      {
        slug: "wip",
        name: "WIP Item",
        name_plural: "Work In Progress (WIP)",
        description: "Unbilled time & expenses (WIP) with aging and lock-up tracking",
        icon: "Hourglass",
        fields: [
          { key: "engagement_ref", label: "Engagement Ref", type: "text", required: true },
          { key: "wip_type", label: "Type", type: "select", options: ["time", "expense", "fixed_fee_milestone", "retainer_overrun"] },
          { key: "value", label: "WIP Value", type: "number" },
          { key: "currency", label: "Currency", type: "text" },
          { key: "period", label: "Period", type: "text" },
          { key: "age_days", label: "Age (days)", type: "number" },
          { key: "next_billable_date", label: "Next Billable Date", type: "date" },
          { key: "write_off_amount", label: "Proposed Write-off", type: "number" },
          { key: "write_off_reason", label: "Write-off Reason", type: "textarea" },
        ],
        default_status_options: ["unbilled", "ready_to_bill", "billed", "partial_writeoff", "fully_writtenoff", "disputed"],
      },
      {
        slug: "invoices",
        name: "Invoice",
        name_plural: "Invoices & Billing",
        description: "Client invoices with realisation rate and collection tracking",
        icon: "Receipt",
        fields: [
          { key: "invoice_no", label: "Invoice No.", type: "text", required: true },
          { key: "client", label: "Client", type: "text", required: true },
          { key: "engagement_ref", label: "Engagement Ref", type: "text" },
          { key: "invoice_date", label: "Invoice Date", type: "date" },
          { key: "due_date", label: "Due Date", type: "date" },
          { key: "fees_amount", label: "Fees Amount", type: "number" },
          { key: "expenses_amount", label: "Expenses Amount", type: "number" },
          { key: "tax_amount", label: "Tax Amount", type: "number" },
          { key: "total_amount", label: "Total", type: "number" },
          { key: "currency", label: "Currency", type: "text" },
          { key: "realisation_pct", label: "Realisation %", type: "number" },
          { key: "po_reference", label: "Client PO Ref", type: "text" },
        ],
        default_status_options: ["draft", "approved", "issued", "partial_paid", "paid", "overdue", "disputed", "credit_note", "written_off"],
      },

      // ---------- CLIENT EXPERIENCE ----------
      {
        slug: "client-feedback",
        name: "Client Feedback",
        name_plural: "Client Feedback (CSAT/NPS)",
        description: "CSAT/NPS responses and qualitative feedback from clients",
        icon: "MessageCircleHeart",
        fields: [
          { key: "client", label: "Client", type: "text", required: true },
          { key: "engagement_ref", label: "Engagement Ref", type: "text" },
          { key: "respondent", label: "Respondent (role)", type: "text" },
          { key: "feedback_type", label: "Feedback Type", type: "select", options: ["mid_engagement_csat", "end_of_engagement_csat", "annual_nps", "ad_hoc_complaint", "ad_hoc_compliment"] },
          { key: "score", label: "Score", type: "number" },
          { key: "scale", label: "Scale", type: "select", options: ["nps_-100_100", "csat_1_5", "csat_1_10", "ces_1_7"] },
          { key: "verbatim", label: "Verbatim Comments", type: "textarea" },
          { key: "follow_up_required", label: "Follow-up Required", type: "select", options: ["none", "thank_you", "investigate", "remediation_plan", "executive_call"] },
        ],
        default_status_options: ["received", "reviewed", "follow_up_in_progress", "closed", "escalated"],
      },
    ],
  },
    name: "Healthcare",
    description: "Clinical projects, compliance and patient initiatives",
    icon: "Stethoscope",
    enabled_modules: ["programmes", "projects", "tasks", "risks", "issues", "reports", "knowledgebase", "incidents", "patient_cohorts"],
    terminology_overrides: { project: "Care Programme", stakeholder: "Patient Group" },
    default_dashboards: ["clinical_overview"],
    ai_context_prompt: "You are assisting a Healthcare team. Use clinical terminology, HIPAA awareness, patient outcomes.",
    entities: [
      {
        slug: "incidents",
        name: "Clinical Incident",
        name_plural: "Clinical Incidents",
        description: "Adverse events, near misses and patient safety reports",
        icon: "AlertTriangle",
        fields: [
          { key: "patient_ref", label: "Patient Reference", type: "text", required: true },
          { key: "severity", label: "Severity", type: "select", options: ["low", "moderate", "severe", "catastrophic"], required: true },
          { key: "narrative", label: "Narrative", type: "textarea", required: true },
        ],
        default_status_options: ["reported", "under_review", "resolved", "escalated"],
      },
    ],
  },
  {
    id: "manufacturing",
    name: "Manufacturing",
    description: "Production lines, work orders and quality control",
    icon: "Factory",
    enabled_modules: ["programmes", "projects", "tasks", "risks", "issues", "reports", "knowledgebase", "work_orders", "quality_checks"],
    terminology_overrides: { project: "Production Run", work_package: "Batch", stakeholder: "Supplier" },
    default_dashboards: ["throughput", "oee"],
    ai_context_prompt: "You are assisting a Manufacturing team. Reference OEE, work orders, lead time, scrap rate, supplier QA.",
    entities: [
      {
        slug: "work-orders",
        name: "Work Order",
        name_plural: "Work Orders",
        description: "Production and maintenance work orders",
        icon: "Wrench",
        fields: [
          { key: "wo_type", label: "Type", type: "select", options: ["production", "maintenance", "inspection"], required: true },
          { key: "asset", label: "Asset / Line", type: "text" },
          { key: "qty", label: "Quantity", type: "number" },
        ],
        default_status_options: ["scheduled", "in_progress", "complete", "on_hold"],
      },
    ],
  },
  {
    id: "education",
    name: "Education",
    description: "Curriculum, courses, learning outcomes and student initiatives",
    icon: "GraduationCap",
    enabled_modules: ["programmes", "projects", "tasks", "risks", "reports", "knowledgebase", "courses"],
    terminology_overrides: { programme: "Curriculum", project: "Course", stakeholder: "Student Cohort" },
    default_dashboards: ["enrolment", "outcomes"],
    ai_context_prompt: "You are assisting an Education team. Reference curriculum design, learning outcomes, accreditation, student engagement.",
    entities: [
      {
        slug: "courses",
        name: "Course",
        name_plural: "Courses",
        description: "Offered courses and modules",
        icon: "BookOpen",
        fields: [
          { key: "code", label: "Code", type: "text", required: true },
          { key: "credits", label: "Credits", type: "number" },
          { key: "level", label: "Level", type: "select", options: ["foundation", "undergrad", "grad", "post-grad"] },
        ],
        default_status_options: ["draft", "approved", "running", "retired"],
      },
    ],
  },
  {
    id: "legal",
    name: "Legal & Professional",
    description: "Matter management, deadlines, document review",
    icon: "Scale",
    enabled_modules: ["programmes", "projects", "tasks", "risks", "issues", "reports", "knowledgebase", "matters"],
    terminology_overrides: { project: "Matter", programme: "Practice Area", stakeholder: "Counterparty" },
    default_dashboards: ["matter_load", "billable_hours"],
    ai_context_prompt: "You are assisting a Legal practice. Reference matters, deadlines, conflicts checks, privilege, disclosure.",
    entities: [
      {
        slug: "matters",
        name: "Matter",
        name_plural: "Matters",
        description: "Legal matters and case files",
        icon: "Gavel",
        fields: [
          { key: "matter_type", label: "Matter Type", type: "select", options: ["litigation", "transactional", "advisory", "compliance"], required: true },
          { key: "client", label: "Client", type: "text", required: true },
          { key: "opposing", label: "Opposing Party", type: "text" },
        ],
        default_status_options: ["open", "discovery", "trial", "settled", "closed"],
      },
    ],
  },
  {
    id: "retail",
    name: "Retail & E-commerce",
    description: "Store ops, merchandising, inventory and seasonal launches",
    icon: "ShoppingBag",
    enabled_modules: ["programmes", "projects", "tasks", "risks", "issues", "reports", "knowledgebase", "store_initiatives"],
    terminology_overrides: { project: "Initiative", stakeholder: "Customer Segment" },
    default_dashboards: ["sales_lift", "shrinkage"],
    ai_context_prompt: "You are assisting a Retail team. Reference store ops, merchandising, seasonal calendar, inventory turn.",
  },
  {
    id: "non_profit",
    name: "Non-profit & NGO",
    description: "Grant programmes, donor relations, impact tracking",
    icon: "HandHeart",
    enabled_modules: ["programmes", "projects", "tasks", "risks", "reports", "knowledgebase", "grants"],
    terminology_overrides: { programme: "Programme", project: "Initiative", stakeholder: "Donor" },
    default_dashboards: ["impact", "grant_pipeline"],
    ai_context_prompt: "You are assisting a Non-profit/NGO team. Reference grants, beneficiaries, theory of change, impact measurement.",
    entities: [
      {
        slug: "grants",
        name: "Grant",
        name_plural: "Grants",
        description: "Grant applications and awards",
        icon: "Award",
        fields: [
          { key: "funder", label: "Funder", type: "text", required: true },
          { key: "amount", label: "Amount", type: "number" },
          { key: "deadline", label: "Application Deadline", type: "date" },
        ],
        default_status_options: ["prospect", "submitted", "awarded", "declined", "reporting"],
      },
    ],
  },
];
