#!/usr/bin/env bash
# Rewrite version strings in onprem docs + scripts.
# Idempotent — safe to re-run.
# Usage: ./update-docs.sh <version>   e.g. ./update-docs.sh 1.4.0
set -euo pipefail
VERSION="${1:?version required}"
TAG="v${VERSION#v}"
cd "$(dirname "$0")/../.."   # repo root
ROOT="$(pwd)"

# Files to update
FILES=(
  "onprem/docs/upgrade.md"
  "onprem/docs/install.md"
  "onprem/docs/README.md"
  "onprem/README.md"
)

# Replace any vN.N.N reference in example commands with $TAG.
# Conservative: only rewrites lines that look like example/CLI usage,
# never freeform prose.
for f in "${FILES[@]}"; do
  [ -f "$ROOT/$f" ] || continue
  # Replace 'vX.Y.Z' on lines that contain pimp-cli, tar -xzf bundles, or download/upgrade examples
  sed -i.bak -E "/(pimp-cli|bundles\/|taskmaster-)v[0-9]+\.[0-9]+\.[0-9]+/ s/v[0-9]+\.[0-9]+\.[0-9]+/$TAG/g" "$ROOT/$f"
  rm -f "$ROOT/$f.bak"
done

# Stamp current version into a single-source-of-truth doc
cat > "$ROOT/onprem/docs/CURRENT_VERSION.md" <<EOF
# Current Release

**Version:** \`$TAG\`
**Updated:** $(date -u +"%Y-%m-%d")

This file is auto-generated by \`onprem/release/update-docs.sh\`.
Do not edit by hand.
EOF

echo "✓ Docs updated to $TAG"
